version: "3.8"

services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
    restart: on-failure
    image: mysql:8.3
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "${APP_PORT}:3306"
    networks:
      - mysql_network
    env_file:
      - .env

volumes:
  mysql_volume:

networks:
  mysql_network:
