version: "3.8"

services:
  redis:
    image: redis:latest
    restart: on-failure
    command: /bin/sh -c "redis-server --requirepass ${PASSWORD}"
    volumes:
      - ./redis:/data
    ports:
      - "${APP_PORT}:6379"
    env_file:
      - .env

volumes:
  redis_volume_data:
