version: "3.8"

services:
  redis:
    image: redis:latest
    restart: on-failure
    command: /bin/sh -c "redis-server --requirepass ${PASSWORD}"
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
    env_file:
      - .env

  redis_insight:
    image: redislabs/redisinsight:latest
    restart: on-failure
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight:/db

volumes:
  redis_volume_data:
  redis_insight_volume_data:
